export const CHANGE_SELECTED_HOME = "CHANGE_SELECTED_HOME";
export const CHANGE_TIMES = "CHANGE_TIMES";
export const CHANGE_CITIES = "CHANGE_CITIES";
export const CHANGE_HOTS = "CHANGE_HOTS";
export const CHANGE_SEARCH_HOUSES = "CHANGE_SEARCH_HOUSES";
export const CHANGE_REFRESH_HOUSE_LOADING = "CHANGE_REFRESH_LOADING";
export const REFRESH_HOUSES = "REFRESH_HOUSES";
